name: bucket_water_oms_admin_mobile
description: 水厂订货管理系统 - 移动端App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^14.0.0
  provider: ^6.1.1
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  http: ^1.1.0
  http_parser: ^4.0.0
  mobile_scanner: ^5.1.1
  map_launcher: ^3.5.0
  url_launcher: ^6.2.0
  image_picker: ^1.0.4
  location: ^6.0.0
  flutter_local_notifications: ^18.0.1
  vibration: ^2.0.0
  audioplayers: ^6.1.0
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
